# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: pernexium
# "service" is the name of this project. This will also be added to your AWS resource names.
service: ana-backend

build:
  esbuild: true

provider:
  name: aws
  runtime: nodejs20.x
  profile: pernexium
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
  environment:
    BUCKET_NAME: ${self:service}-storage-${sls:stage}
    ANA_API_URL: https://ow24p7ablb.execute-api.us-east-1.amazonaws.com
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::${self:service}-storage-${sls:stage}/*
            - arn:aws:s3:::${self:service}-storage-${sls:stage}

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
          cors: true

  uploadBackup:
    handler: src/handlers/backups.uploadBackup
    events:
      - httpApi:
          cors: true
          path: /backups
          method: post

  getLatestBackup:
    handler: src/handlers/backups.getLatestBackup
    events:
      - httpApi:
          cors: true
          path: /backups/latest/{agentId}/{campaign}
          method: get

  getChats:
    handler: src/handlers/chats.getChats
    events:
      - httpApi:
          path: /get/chats/{agentId-campaign-id}
          method: get
          cors: true

  uploadMedia:
    handler: src/handlers/media.uploadMedia
    events:
      - httpApi:
          path: /media
          method: post
          cors: true

  updatePendingContacts:
    handler: src/handlers/contacts.updatePendingContacts
    events:
      - httpApi:
          path: /contacts/pending
          method: post
          cors: true

resources:
  Resources:
    StorageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-storage-${sls:stage}
